services:
  postgres:
    image: postgres:latest
    container_name: postgres_vmestego
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: db-vmestego
    ports:
      - "5432:5432"
    volumes:
      - vmestego_pgdata:/var/lib/postgresql/data

volumes:
  vmestego_pgdata: