version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_vmestego
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: db-vmestego
    ports:
      - "5432:5432"
    volumes:
      - vmestego_pgdata:/var/lib/postgresql/data

  vmestego:
    build: .
    container_name: vmestego
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Postgres: Host=postgres;Port=5432;Database=db-vmestego;Username=postgres;Password=postgrespw
    depends_on:
      - postgres

volumes:
  vmestego_pgdata: